// <auto-generated />
namespace ASP_MVC_Backpackes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_require : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_require));
        
        string IMigrationMetadata.Id
        {
            get { return "201801202204454_change_require"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
